---
# Desktop applications

- name: Install GUI applications
  become: true
  ansible.builtin.dnf:
    name:
      - solaar
      - firefox
      - kitty
      - ghostty
      - gnome-tweaks
      - gnome-extensions-app
    state: present
