# External binary versions
# Renovate will update these versions, and they'll be substituted into download URLs
# Format: tool = "version" # renovate: datasource=github-releases depName=owner/repo

[versions]
  cliphist = "0.7.0"  # renovate: datasource=github-releases depName=sentriz/cliphist
