[aws]
disabled = false
symbol = "  "

[character]
error_symbol = "[~~>](bold red) "
success_symbol = "[=>>](bold green) "
vimcmd_replace_one_symbol = "[<<=](bold purple) "
vimcmd_replace_symbol = "[<<=](bold purple) "
vimcmd_symbol = "[<<=](bold yellow) "
vimcmd_visual_symbol = "[<<=](bold cyan) "

[cmd_duration]
disabled = false
format = "  [$duration]($style) "
min_time_to_notify = 180000
show_notifications = true

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
fish_style_pwd_dir_length = 1
read_only = " "
truncation_length = 3
truncation_symbol = "…/"

[docker_context]
disabled = false
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fill]
disabled = false
symbol = " "

[gcloud]
disabled = false
symbol = " "

[git_branch]
disabled = false
symbol = " "

[git_commit]
disabled = false
only_detached = false
tag_disabled = false

[git_metrics]
disabled = false

[git_status]
disabled = false
deleted = "󱂥 "
ahead = "󰩍 "
behind = "󰥥 "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
format = "[@$hostname]($style) in "
ssh_only = false
ssh_symbol = "󰣀  "
style = "#8aadf4"

[java]
symbol = " "

[julia]
symbol = " "

[kubernetes]
disabled = false

[memory_usage]
symbol = "󰍛  "

[nix_shell]
disabled = false
impure_msg = ""
symbol = " "

[nodejs]
symbol = " "

[os]
disabled = false
style = "bold blue"
[os.symbols]
Fedora = "  "
Arch = "󰣇 "

[package]
symbol = "  "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
disabled = true
repeat = false
threshold = 2

[status]
disabled = false
map_symbol = true
sigint_symbol = "‼️"
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '

[terraform]
symbol = "󱁢 "

[time]
disabled = false

[username]
format = "[$user]($style)"
show_always = true
style_root = "#ed8796"
style_user = "#f4dbd6"
