services:
  systemd:
    mask:
      - gcr-ssh-agent.socket
      - gcr-ssh-agent.service
      - app-org.kde.xwaylandvideobridge@autostart.service
    start_only:
      - syncthing.service
    enable_restart:
    enable_start:
      - app-com.mitchellh.ghostty.service
      - podman.socket
      - podman-auto-update.timer
      - vicinae.service
